force-app/main/default/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

force-app/main/default/objects/hed__Course_Enrollment__c/recordTypes/Student_Pending.recordType-meta.xml
<RecordType>
    <fullName>Student_Pending</fullName>
    <active>true</active>
    <description>Student Enrollment that exists but is not confirmed.</description>
    <label>Student - Pending</label>
</RecordType>

force-app/main/default/objects/hed__Course_Offering__c/fields/Avg_Grade_Point__c.field-meta.xml
<CustomField>
    <fullName>Avg_Grade_Point__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Average Grade point in the section.</description>
    <inlineHelpText>Average Grade point in the section.</inlineHelpText>
    <label>Average Grade Point</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/hed__Course_Offering__c/fields/Confirmed_Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Enrollments__c</fullName>
    <description>The count of confirmed student course connections. This is set in an after insert/update/delete trigger on Course Connection.</description>
    <inlineHelpText>The count of confirmed student course connections. This is set in an after insert/update/delete trigger on Course Connection.</inlineHelpText>
    <label>Confirmed Enrollments</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/hed__Course_Offering__c/fields/Pending_Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Pending_Enrollments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The count of pending student course connections. This is set in an after insert/update/delete trigger on Course Connection.</description>
    <inlineHelpText>The count of pending student course connections. This is set in an after insert/update/delete trigger on Course Connection.</inlineHelpText>
    <label>Pending Enrollments</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/background/CourseOfferingAggregates.cls
global class CourseOfferingAggregates {
    
    @future
    public static void updateOfferingAggregates(List<Id> offeringIds) {
        AggregateResult[] enrollmentCounts = [SELECT hed__Course_Offering__c, RecordType.DeveloperName, COUNT(Id)Enrollment_Count, AVG(hed__Grade__c)Avg_Grade FROM hed__Course_Enrollment__c WHERE hed__Course_Offering__c IN :offeringIds GROUP BY hed__Course_Offering__c, RecordType.DeveloperName];
    
        Map<Id, hed__Course_Offering__c> toUpdate = new Map<Id, hed__Course_Offering__c>();
        for(AggregateResult enrollmentCount : enrollmentCounts) {
            Id offeringId = (Id) enrollmentCount.get('hed__Course_Offering__c');
            String recordTypeName = (String) enrollmentCount.get('DeveloperName');
            Integer counts = (Integer) enrollmentCount.get('Enrollment_Count');
            Double avgGrade = (Double) enrollmentCount.get('Avg_Grade');

            hed__Course_Offering__c offering = toUpdate.get(offeringId);
            if(offering == null) {
                offering = new hed__Course_Offering__c(Id = offeringId, Confirmed_Enrollments__c = 0, Pending_Enrollments__c = 0, Avg_Grade_Point__c = 0.00);
                toUpdate.put(offeringId, offering);
            }
            if(recordTypeName == 'Student') {
                offering.Confirmed_Enrollments__c = counts;
                offering.Avg_Grade_Point__c = avgGrade;
            } else if(recordTypeName == 'Student_Pending') {
                offering.Pending_Enrollments__c = counts;
            }
        }

        if(!toUpdate.isEmpty()) {
            // For large updates, row locks can stop this. Don't fail just because we can't update everything.
            while(!toUpdate.isEmpty()) {
                List<Database.SaveResult> saveResults = Database.update(toUpdate.values(), false, System.AccessLevel.SYSTEM_MODE);
                for(Database.SaveResult saveResult : saveResults) {
                    if(saveResult.success) {
                        toUpdate.remove(saveResult.id);
                    }
                }
            }
        }
    }

}