force-app/main/default/objects/Marketing_Cloud_Journey_Event__c/Marketing_Cloud_Journey_Event__c.object-meta.xml
<CustomObject>
    <description>Custom Object to hook into for MC journey initiations.</description>
    <label>Marketing Cloud Journey Event</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Cloud Journey Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Cloud_Journey_Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Identifier for the journey - can be key or whatever.</description>
    <inlineHelpText>Identifier for the journey - can be key or whatever.</inlineHelpText>
    <label>Event</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Journey_Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Type of the event.</description>
    <inlineHelpText>Type of the event.</inlineHelpText>
    <label>Event Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Journey_Event__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique key per journey init.</description>
    <inlineHelpText>It&apos;s recommended to concatenate the event type here because this field must be entirely unique.</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AzureEventIntegration_TEST.cls
@IsTest
global class AzureEventIntegration_TEST {

    @IsTest
    private static void sendEvents() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, BaseTestUtil.getEventCalloutMock());
        AzureEventIntegration.AzureResponse response = AzureEventIntegration.sendEvents(new List<AzureEventIntegration.AzureEvent>{new AzureEventIntegration.AzureEvent('topic', 'eventType', 'subject', new Map<String, Object> {'test' => 'test'})}, false);
        Test.stopTest();

        System.assert(response.success);
    }

    @IsTest
    private static void getAccount() {
        RecordType deptType = [select Id from RecordType where DeveloperName = 'Administrative' LIMIT 1];
        List<AccountRequestor.AccountRequest> requests = new List<AccountRequestor.AccountRequest>{new AccountRequestor.AccountRequest(deptType.Id, 'CSUOEE')};
        
        List<Account> accts = AccountRequestor.getAccount(requests);

        System.assert(accts.get(0) == null);

        Account acct = new Account(Name = 'test', RecordTypeId = deptType.Id, hed__School_Code__c = 'CSUOEE');
        insert acct;

        accts = AccountRequestor.getAccount(requests);
        System.assert(accts.get(0) != null);
    }

    @IsTest
    private static void constructorCoverage() {
        FlowDelayConfiguration test1 = FlowDelayConfiguration.DayDelay(1);
        System.assertEquals('Days', test1.getDelayIncrement());
        System.assertEquals(1, test1.getDelayAmount());
        
        FlowDelayConfiguration test2 = FlowDelayConfiguration.HourDelay(1);
        System.assertEquals('Hours', test2.getDelayIncrement());
        System.assertEquals(1, test2.getDelayAmount());

        Test.startTest();
        Marketing_Cloud_Journey_Event__c event = new Marketing_Cloud_Journey_Event__c(Event__c = 'test', Event_Type__c = 'test type', Key__c = 'test');
        try {
            insert event;
        } catch(System.DmlException e) {
            System.assert(true);// This should fail on custom exception
        }
        Test.stopTest();
    }
    
}