force-app/main/default/objects/Contact/fields/CSU_ID__c.field-meta.xml
<CustomField>
    <fullName>CSU_ID__c</fullName>
    <description>The CSU ID for a student record.</description>
    <externalId>true</externalId>
    <inlineHelpText>The CSU ID for a student record.</inlineHelpText>
    <label>CSU ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/rest/CpsUpsert.cls
@RestResource(urlMapping = '/contact/cps')
public class CpsUpsert {

    @HttpPost
    public static Map<String, String> upsertCpsContact(Contact cpsContact) {
        // OK - First, CSU_ID
        if(cpsContact.CSU_ID__c != null) {
            // Great - we MUST have them, so don't do an update!
            return new Map<String, String> {'success' => 'true', 'message' => 'CSU_ID set, no update.'};
        }

        Contact instructor = [SELECT Id from Contact where Email = :cpsContact.Email or hed__University_Email__c = :cpsContact.Email LIMIT 1];

    }
    
}