force-app/main/default/objects/Contact/fields/EID__c.field-meta.xml
<CustomField>
    <fullName>EID__c</fullName>
    <description>The electronic ID for the student.</description>
    <inlineHelpText>The electronic ID for the student.</inlineHelpText>
    <label>EID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/hed__Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <description>The Prefix &amp; Number combo for a course</description>
    <externalId>true</externalId>
    <inlineHelpText>e.g. ACT 205</inlineHelpText>
    <label>Course Code</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/hed__Term__c/fields/lms_hed__LMS_Reference_Code__c.field-meta.xml
<CustomField>
    <fullName>lms_hed__LMS_Reference_Code__c</fullName>
    <description>A reference code for a term - uniquely identifies it. e.g. Spring 2023 -&gt; 2023SP.</description>
    <externalId>true</externalId>
    <inlineHelpText>A reference code for a term - uniquely identifies it. e.g. Spring 2023 -&gt; 2023SP.</inlineHelpText>
    <label>LMS Reference Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CombinedFunctions_TEST.cls
@IsTest
private class CombinedFunctions_TEST {

    @IsTest
    private static void handleEnrollments() {
        Account dept = new Account(Name = 'Test Dept');
        insert dept;

        Contact contact = new Contact(LastName = 'Test', EID__c = 'test-eid');
        insert contact;

        hed__Term__c term = new hed__Term__c(Name = '2023SP', hed__Account__c = dept.Id);
        insert term;

        hed__Course__c course = new hed__Course__c(hed__Account__c = dept.Id, Name = 'CO 333', hed__Course_ID__c = 'CO 333', Course_Code__c = 'CO 333');
        insert course;

        hed__Course_Offering__c offering = new hed__Course_Offering__c(Name = 'CO 333 100', hed__Course__c = course.Id, hed__Term__c = term.Id, hed__Section_ID__c = '100', lms_hed__LMS_Reference_Code__c = '2023SP-CO-333-100');
        insert offering;

        Test.startTest();
        CombinedFunctions.EnrollmentRequest request = new CombinedFunctions.EnrollmentRequest();
        request = new CombinedFunctions.EnrollmentRequest('test-eid', '2023SP-CO-333-100', false);
        System.assert(request != null);

        hed__Course_Enrollment__c enrollment = CombinedFunctions.handleStudentEnrollment(contact, '2023SP-CO-333-100', false);
        System.assert(enrollment != null);
        CombinedFunctions.handleStudentEnrollment(contact, '2023SP-CO-333-100', true);

        enrollment = CombinedFunctions.handleInstructorEnrollment(contact, '2023SP-CO-333-100', false);
        System.assert(enrollment != null);
        CombinedFunctions.handleInstructorEnrollment(contact, '2023SP-CO-333-100', true);

        enrollment = CombinedFunctions.handleInstructorEnrollment(contact, '2023SP-CO-333-1', false);
        System.assert(enrollment == null);

        Test.stopTest();
    }
    
}